### ISSUE TITLE
Trailing semi-colon in SQL statements should be discarded

### ISSUE THREAD

**Issue by Tux** [perl5-dbi/DBD-CSV#2]
Forwarding an issue mailed in private:

Most SQL bases either requires or permits ; following a statement. Not so for DBD::CSV.

That seems like a bug, because that makes it harder to switch to DBD::CSV.

Works:
    $dbh->do ("CREATE TABLE foo (id INTEGER, name CHAR (10))");

Fails:
    $dbh->do ("CREATE TABLE foo (id INTEGER, name CHAR (10));");

The second works fine for SQLite, MySQL and PostgreSQL.

**Comment by Tordek** [comment]
From what I can tell, this is from DBI. It says:

> Some command-line SQL tools use statement terminators, like a semicolon, to indicate the end of a statement. Such terminators should not normally be used with the DBI.

https://metacpan.org/pod/DBI#prepare

**Comment by Tordek** [comment]
Perhaps this should be fixed in `SQL::Statement`? does it affect DBD::DBM, ::Excel and so on?

Edit: Indeed it does.

**Comment by Tux** [comment]
I just pushed the fix to DBI::SQL::Nano and to SQL::Statement.
The first will be included in the forthcoming DBI release
The second will depend on if Jens accepts the change ans includes it in the next release
