### ISSUE TITLE
csv_ prefix is mandatory for eol attribute in csv_tables hash ref

### ISSUE THREAD

**Issue by XSven** [perl5-dbi/DBD-CSV#7]
Although I could not figure out why the csv_ prefix seems to be mandatory for the eol attribute, if used inside the csv_tables hash ref.

Does not work. Uses the default "\r\n" instead of "\n" only.
```
csv_tables       => {
  my_table => {
    eol => "\n"
  }
}      
```

Works
```
csv_tables       => {
  my_table => {
    csv_eol => "\n"
  }
}      
```

**Comment by Tux** [comment]
That is because of the DBD::File driver being in the middle

**Comment by XSven** [comment]
Is this a bug or simply an annoying inconvenience? I would at least appreciate a fix of the documentation that currently says about the attributes of the cvs_tables hash ref

`
All valid attributes to the CSV parsing module. Any of the can optionally be prefixed with csv_.
`

**Comment by Tux** [comment]
It has been a while (sorry), and that is partly because I never use `{csv_tables}` myself.
I have just pushed cf0710d215f75440 which is to address this issue. Care to test that and give feedback?

**Comment by Tux** [comment]
Now pushed in b31dda6e6447b with tests. This will be in the next release, so I close this issue.
